-- SQL schema for AGM MD5 FLOATING ANALYZER Backend

-- Table to store sessions and keys for activation
CREATE TABLE IF NOT EXISTS access_sessions (
    id TEXT PRIMARY KEY,               -- Session ID
    installation_id TEXT NOT NULL,     -- UUID generated by app
    key_hash TEXT NOT NULL,            -- Hash (SHA-256) of the generated key
    attempts INTEGER NOT NULL DEFAULT 0, -- Limit to 5 attempts
    used INTEGER NOT NULL DEFAULT 0,    -- 0: false, 1: true
    created_at TEXT NOT NULL,          -- ISO date string
    expires_at TEXT NOT NULL           -- ISO date string
);

-- Table to log link generation rate limits
CREATE TABLE IF NOT EXISTS link_logs (
    id TEXT PRIMARY KEY,
    installation_id TEXT NOT NULL,
    created_at TEXT NOT NULL           -- ISO date string
);
